### ISSUE TITLE
ngBusy directive with subscription 

### ISSUE THREAD

**Issue by davidgiggs** [victos/angular-opensource#1]
Hi,
We are trying to use your ngbusy directive using your 6.0.0-alpha1 version. 

This works fine using the ngbusy directive when parsing in an array or busy config (via object syntax), but the directive does not seem to work when passing a subscription object from a component. 

e.g. 
These work fine:-
<div [ngBusy]="[busyService.busy]" class="row"></div>
<div [ngBusy]="{busy: busyService.busy}" class="row">

But this doesn't :-
  <div [ngBusy]="busyService.busy" class="row"></div>

Our busyService.busy simply returns a subscription from "rxjs" (we are using RxJs 6.0.0.).

**Comment by victos** [comment]
Hi @davidgiggs ,
I've fix this and release a new version 6.0.0-alpha2. Thanks for your feedback.

**Comment by davidgiggs** [comment]
Hi there, 
Looks good! Closing as issue is fixed.
