### ISSUE TITLE
Custom template component

### ISSUE THREAD

**Issue by benshabatnoam** [victos/angular-opensource#11]
I have a question.
I'm trying to implement your solution for custom template component.
I've managed to do so. The problem I ran into is customize the template component. e.g. pass with and height values that will change the template size.
Can you help me, how do I manage to do so?
10x

**Comment by victos** [comment]
Hi,
Sorry I can't understand the problem completely. Could you please provide a demo , like [this](https://stackblitz.com/edit/angular-prwxkv?file=src%2Fapp%2Fcomponents%2Fmy-spinner%2Fmy-spinner.component.ts) one?

**Comment by benshabatnoam** [comment]
Hi again,
10x for the reply.
this is the modified [demo](https://stackblitz.com/edit/angular-qdakxt?embed=1&file=src/app/components/my-spinner/my-spinner.component.ts).
10x again

**Comment by victos** [comment]
Hi,
Why not use the wrapperClass in the config, I think you can use this to change the style of the customize template.

**Comment by benshabatnoam** [comment]
You are right, I can do that, but that way I can't change the style dynamically.
Lets say I want the loading circle to be top 100 from one place, and in another place I need it 200, and so on...
That way I will need a CSS class for each one of them.

**Comment by victos** [comment]
Hi, 
Maybe I will implement this in the next release.

**Comment by benshabatnoam** [comment]
Cool. I can help with that if you would like to. 10x

**Comment by victos** [comment]
Yes, of course you can. Then we'll have the release very soon :+1: .

**Comment by victos** [comment]
go alive with 6.2.0

**Comment by benshabatnoam** [comment]
Great! 10x
