### ISSUE TITLE
Why can't I use the same subscription obj on different divs? One of them is displayed

### ISSUE THREAD

**Issue by yousefkhan** [victos/angular-opensource#14]
I have structure like 

```
<div class="position-relative">
   <div [ngBusy]="subscription"> </div>
<div>

<div class="position-relative">
    <div [ngBusy]="subscription"> </div>
<div>

```
These divs have totally different positions on single page. But top one of them is displayed, removing the one displays the other one. Not sure if I am using in a wrong way or making any mistake.

**Comment by victos** [comment]
I never test it in that scenario, maybe we can't use this in that way.

**Comment by slenderock** [comment]
Any suggestions for this?
I'm experiencing exactly the same issue as @yousefkhan had
Have you fixed this somehow?

**Comment by victos** [comment]
Sorry, I can not reproduce this issue now, could you guys make a online demo? Maybe on https://stackblitz.com
