### ISSUE TITLE
The spinner and the text are not visible if page has scrolled down

### ISSUE THREAD

**Issue by ghost** [victos/angular-opensource#17]
The spinner and 'Please wait' text are not visible if the page has been scrolled down.

The issue is partially fixed if the following css is added  [from here](https://github.com/devyumao/angular2-busy/issues/63)
`.ng-busy-default-spinner, .ng-busy-backdrop {
      position: fixed;
}`

The spinner is displayed alright, but the text 'Please wait' is gone.
Any ideas how to fix this?

**Comment by victos** [comment]
The spinner is supposed to cover the element which has the directive ngBusy, so if the element is can't be seen in the page, we can't see the spinner. Maybe you can place the directive ngBusy on the body or root div in the page.

**Comment by salifukayta** [comment]
Good to know, I did put the directive on an element with an *ngIf and wondered why it's not working.
Thanks for the information :)
