### ISSUE TITLE
Feature: Automatically toPromise() Observables

### ISSUE THREAD

**Issue by noskap** [victos/angular-opensource#18]
Currently [ngBusy] only works with Promises or an Observables' Subscription. I'm using a lot of async pipes in my code, so I never have to subscribe to Observables in the components. A workaround is calling toPromise() on an observable before passing it to ngBusy. It would be cleaner if ngBusy allowed us to use Observables from the start without having to toPromise them or manually subscribe

**Comment by noskap** [comment]
Feel free to use my fork as a base
https://github.com/noskap/angular-opensource/tree/master/projects/ng-busy

**Comment by jaufgang** [comment]
@noskap, your ng-busy-observable is now out of date and not compatible with newer versions of angular.  Instead of publishing your update as as separate package, perhaps consider making a PR to this package to support passing an observable?
