### ISSUE TITLE
Cannot redeclare block-scoped variable 'ngDevMode'

### ISSUE THREAD

**Issue by bm-software** [victos/angular-opensource#2]
After the ugrade to angular 6.0.3 and ng-busy ^6.0.0-rc0 I get the error:

`Cannot redeclare block-scoped variable 'ngDevMode'` 

when the app is running in dev.
I notice that inside ng-busy folder in node_modules folder there is another node_modules folder with core, common and animations modules installed.
These are duplicates as of I installed those dependencies in through the app root packages.json.

How can I solve?

**Comment by victos** [comment]
Hi, @bm-software 
The problem occurred when I use yarn to install the dependencies, and when I use npm to install the dependencies, everything goes well.

**Comment by victos** [comment]
I'v release a new version 6.0.0.rc1 that remove the dependencies, this version works well with yarn. Thanks for your report.

**Comment by bm-software** [comment]
@victos Thank you very much!
