### ISSUE TITLE
Directive isn't accepting options

### ISSUE THREAD

**Issue by buddyackerman** [victos/angular-opensource#24]
Tried to implement a delay in this way

<div class="container" [ngBusy]="busy" delay="500">

Are the options not implemented as @Input properties?

**Comment by Betalos** [comment]
@buddyackerman could be more specific in your issue.
What is the problem exactly that you're facing.

**Comment by buddyackerman** [comment]
I was hoping that the this directive would allow you to set the options on the element itself, e.g.: 

<div [ngBusy]="busy" delay="500">some content</div>

That way the behavior could be modified for each context in which it is used.

**Comment by Betalos** [comment]
Ah I see for that you need to pass the config to the directive as an object like this:
```html
<div [ngBusy]="{busy: busy: delay: 500}">some content</div>
```
