### ISSUE TITLE
[Question] How can I make the busy indicator showing for the div, not for the whole page?

### ISSUE THREAD

**Issue by phuctv95** [victos/angular-opensource#29]
I'm trying to make the busy indicator showing only for the div that is declaring the `[ngBusy]`, but the actual result is it shows for the whole page.

I make a demo here: https://stackblitz.com/edit/angular-ivy-9zygom

![gtpBZ5SgtT](https://user-images.githubusercontent.com/20752858/137187535-8ca11eb2-3d4f-4ff7-847c-92fe91723bcc.gif)

Did I do something wrong?

**Comment by victos** [comment]
https://stackblitz.com/edit/angular-ivy-qjvg5h?file=src%2Fapp%2Fchild%2Fchild.component.html

here's a solution, I add a parent div for the target with class `busy-box` with style `position: relative;`

**Comment by phuctv95** [comment]
the solution works, thank you! 👍
